### ISSUE TITLE
Input Mouse wheel is not detecting, scrolling doesn't happen with mouse wheel

### ISSUE THREAD

**Issue by VikSin** [britzl/extension-imgui#40]

**Comment by britzl** [comment]
The issue was that mouse state must be set in `on_input` and not `update` to ensure that mouse states are set before the next imgui frame is draw.

I've added `imgui.set_mouse_button(index, button)`, `imgui.set_mouse_wheen(value)` and `imgui.set_mouse_pos(x, y)` so that the mouse values can be updated in `on_input()` rather than `update()`.
