### ISSUE TITLE
Getting error with font_push methods while using imgui with monarch screen manager scene

### ISSUE THREAD

**Issue by VikSin** [britzl/extension-imgui#41]
Getting error with font_push and font_pop methods while using imgui screen as monarch scene

Example test project-
[imgui_test.zip](https://github.com/britzl/extension-imgui/files/14122267/imgui_test.zip)

https://github.com/britzl/extension-imgui/assets/25245765/819cb125-6119-467b-a757-d88e17400324

**Comment by britzl** [comment]
It seems to happen if the collection is loaded with "async_load". It works while loading using "load". Not sure what the problem is to be honest.

My recommendation is that you load fonts immediately on startup in main.script and store the references/font ids in a Lua module which you require and use from imgui_manager.script.
